/*
 * WTF-o-meter
 * Code is measured by wtfs per minute
 *
 * OpenAPI spec version: 1
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.dotsource.wtf.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Line
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-10-25T21:44:05.231Z")
public class Line {
  @JsonProperty("lineno")
  private Integer lineno = null;

  @JsonProperty("thumbsup")
  private Integer thumbsup = null;

  @JsonProperty("thumbsdown")
  private Integer thumbsdown = null;

  @JsonProperty("average")
  private Double average = null;

  public Line lineno(Integer lineno) {
    this.lineno = lineno;
    return this;
  }

   /**
   * Get lineno
   * @return lineno
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getLineno() {
    return lineno;
  }

  public void setLineno(Integer lineno) {
    this.lineno = lineno;
  }

  public Line thumbsup(Integer thumbsup) {
    this.thumbsup = thumbsup;
    return this;
  }

   /**
   * Get thumbsup
   * @return thumbsup
  **/
  @ApiModelProperty(value = "")
  public Integer getThumbsup() {
    return thumbsup;
  }

  public void setThumbsup(Integer thumbsup) {
    this.thumbsup = thumbsup;
  }

  public Line thumbsdown(Integer thumbsdown) {
    this.thumbsdown = thumbsdown;
    return this;
  }

   /**
   * Get thumbsdown
   * @return thumbsdown
  **/
  @ApiModelProperty(value = "")
  public Integer getThumbsdown() {
    return thumbsdown;
  }

  public void setThumbsdown(Integer thumbsdown) {
    this.thumbsdown = thumbsdown;
  }

  public Line average(Double average) {
    this.average = average;
    return this;
  }

   /**
   * Get average
   * @return average
  **/
  @ApiModelProperty(value = "")
  public Double getAverage() {
    return average;
  }

  public void setAverage(Double average) {
    this.average = average;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Line line = (Line) o;
    return Objects.equals(this.lineno, line.lineno) &&
        Objects.equals(this.thumbsup, line.thumbsup) &&
        Objects.equals(this.thumbsdown, line.thumbsdown) &&
        Objects.equals(this.average, line.average);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lineno, thumbsup, thumbsdown, average);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Line {\n");
    
    sb.append("    lineno: ").append(toIndentedString(lineno)).append("\n");
    sb.append("    thumbsup: ").append(toIndentedString(thumbsup)).append("\n");
    sb.append("    thumbsdown: ").append(toIndentedString(thumbsdown)).append("\n");
    sb.append("    average: ").append(toIndentedString(average)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

